### ISSUE TITLE
Add new Menu will not support responsive 

### ISSUE THREAD

**Issue by dontmint** [loveminimal/hexo-theme-zero#3]
Hello,

I want to say I really love your theme, thank you for creating this.

I want to add more menu in `themes/zero/_config.yml`
```
menu:
  Home: /
  Github: https://github.com/dontmint
  Twitter: https://github.com/dontmint
```
It shows up correctly but it's not responsive, please help me with this, thank you.
